name: e_book_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  cloud_firestore: ^4.8.4
  equatable: ^2.0.3
  firebase_core: ^2.1.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  freezed_annotation: ^2.4.1
  google_fonts: ^4.0.0
  http: ^1.1.0
  in_app_purchase: ^3.1.8
  intl: any
  meta: ^1.7.0
  shared_preferences: ^2.2.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  generate: true
  assets:
    - assets/google_logo.svg
    - assets/user_profile_photo.png

dependency_overrides:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1
