name: e_book_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  cloud_firestore: ^4.8.4
  equatable: ^2.0.3
  firebase_core: ^2.1.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  freezed_annotation: ^2.4.1
  google_fonts: ^4.0.0
  html: ^0.15.4
  http: ^1.1.0
  in_app_purchase: ^3.1.8
  intl: any
  meta: ^1.7.0
  shared_preferences: ^2.2.0
  webview_flutter: ^4.2.4

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

  flutter_lints: ^2.0.0

flutter_native_splash:
  image: "assets/icon_e_book_app_for_splash.png"
  color: "#ffffff"
  android_disable_fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_ebook.png"
  image_path_android: "assets/icon_ebook.png"
  adaptive_icon_background: "assets/icon_ebook.png"
  adaptive_icon_foreground: "assets/icon_ebook.png"
  min_sdk_android: 19 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/google_logo.svg
    - assets/user_profile_photo.png
    - assets/on_board_page.png
    - assets/icon_e_book_app_for_splash.png

dependency_overrides:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1
